name: ci
on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: install golint
      run: go get -u golang.org/x/lint/golint
    - name: go lint
      run: golint -set_exit_status=1 ./...
